<?php

namespace Medeiros\TesteBundle\Repository;

/**
 * pacienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pacienteRepository extends \Doctrine\ORM\EntityRepository
{
}
